# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{asf-rest-adapter}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Raymond Gao @ Are4Us Technologies"]
  s.date = %q{2011-02-23}
  s.description = %q{REST based adapter for Salesforce}
  s.email = %q{raygao2000@yahoo.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "asf-rest-adapter.gemspec",
    "lib/Salesforce/rest/asf_connection.rb",
    "lib/Salesforce/rest/asf_rest.rb",
    "lib/Salesforce/rest/asf_rest_error.rb",
    "lib/Salesforce/rest/asf_rest_original.rb",
    "lib/Salesforce/rest/classes/account.rb",
    "lib/Salesforce/rest/classes/account_feed.rb",
    "lib/Salesforce/rest/classes/apex_log.rb",
    "lib/Salesforce/rest/classes/asset.rb",
    "lib/Salesforce/rest/classes/asset_feed.rb",
    "lib/Salesforce/rest/classes/campaign.rb",
    "lib/Salesforce/rest/classes/campaign_feed.rb",
    "lib/Salesforce/rest/classes/case.rb",
    "lib/Salesforce/rest/classes/case_feed.rb",
    "lib/Salesforce/rest/classes/case_team_member.rb",
    "lib/Salesforce/rest/classes/case_team_role.rb",
    "lib/Salesforce/rest/classes/contact.rb",
    "lib/Salesforce/rest/classes/contact_feed.rb",
    "lib/Salesforce/rest/classes/contract.rb",
    "lib/Salesforce/rest/classes/contract_feed.rb",
    "lib/Salesforce/rest/classes/entity_subscription.rb",
    "lib/Salesforce/rest/classes/feed_comment.rb",
    "lib/Salesforce/rest/classes/feed_post.rb",
    "lib/Salesforce/rest/classes/feed_tracked_change.rb",
    "lib/Salesforce/rest/classes/group.rb",
    "lib/Salesforce/rest/classes/group_member.rb",
    "lib/Salesforce/rest/classes/lead.rb",
    "lib/Salesforce/rest/classes/lead_feed.rb",
    "lib/Salesforce/rest/classes/news_feed.rb",
    "lib/Salesforce/rest/classes/opportunity.rb",
    "lib/Salesforce/rest/classes/opportunity_feed.rb",
    "lib/Salesforce/rest/classes/organization.rb",
    "lib/Salesforce/rest/classes/product2.rb",
    "lib/Salesforce/rest/classes/product2_feed.rb",
    "lib/Salesforce/rest/classes/solution.rb",
    "lib/Salesforce/rest/classes/solution_feed.rb",
    "lib/Salesforce/rest/classes/solution_history.rb",
    "lib/Salesforce/rest/classes/task.rb",
    "lib/Salesforce/rest/classes/task_feed.rb",
    "lib/Salesforce/rest/classes/user.rb",
    "lib/Salesforce/rest/classes/user_feed.rb",
    "lib/Salesforce/rest/classes/user_profile_feed.rb",
    "lib/Salesforce/rest/classes/user_role.rb",
    "lib/asf-rest-adapter.rb",
    "nbproject/private/private.properties",
    "nbproject/private/private.xml",
    "nbproject/project.properties",
    "nbproject/project.xml",
    "test/helper.rb",
    "test/test_asf-rest-adapter.rb"
  ]
  s.homepage = %q{http://github.com/raygao/asf-rest-adapter}
  s.licenses = ["Apache 2.0"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{REST based adapter for Salesforce}
  s.test_files = [
    "test/helper.rb",
    "test/test_asf-rest-adapter.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_runtime_dependency(%q<asf-soap-adapter>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<asf-soap-adapter>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<asf-soap-adapter>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
  end
end

